CadeteriaWeb/CadeteriaWeb/Models/CadeteDTO.cs
using System.ComponentModel.DataAnnotations;

namespace CadeteriaWeb.Models
{
    public class CadeteDTO
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string direccion { get; set; }
    }
}

CadeteriaWeb/CadeteriaWeb/Models/ClienteDTO.cs
using System.ComponentModel.DataAnnotations;

namespace CadeteriaWeb.Models
{
    public class ClienteDTO
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="el campo es obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "el campo es obligatorio")]
        public string direccion { get; set; }
    }
}

CadeteriaWeb/CadeteriaWeb/Models/ErrorViewModel.cs
namespace CadeteriaWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadeteriaWeb/CadeteriaWeb/Models/HomeIndexViewModel.cs
namespace CadeteriaWeb.Models
{
    public class HomeIndexViewModel
    {
        public IEnumerable<ClienteDTO> ClienteDTOs { get; set; }
        public IEnumerable<CadeteDTO> CadeteDTOs { get; set; }
    }
}

CadeteriaWeb/CadeteriaWeb/Controllers/CadeteController.cs
using CadeteriaWeb.Models;
using CadeteriaWeb.servicios;
using Microsoft.AspNetCore.Mvc;

namespace CadeteriaWeb.Controllers
{
    public class CadeteController : Controller
    {
        private readonly ILogger<CadeteController> _logger;
        private readonly IRepositorioCadete repositorioCadete;

        public CadeteController(ILogger<CadeteController> logger, IRepositorioCadete repositorioCadete)
        {
            _logger = logger;
            this.repositorioCadete = repositorioCadete;
        }
        public IActionResult Index()
        {
            List<CadeteDTO> cadetes = repositorioCadete.listar();
            var modelo = new HomeIndexViewModel()
            {
                CadeteDTOs = cadetes
            };
            return View(modelo);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(CadeteDTO cadeteDTO)
        {
            repositorioCadete.RegistrarCadete(cadeteDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int idCadete)
        {
            var cadete = repositorioCadete.ObtenerId(idCadete);
            return View(cadete);
        }

        [HttpPost]
        public IActionResult Editar(CadeteDTO cadete)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var accion = repositorioCadete.Editar(cadete);
            if (accion)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        
        public IActionResult Eliminar(int idCadete)
        {
            var cadete = repositorioCadete.ObtenerId(idCadete);
            return View(cadete);
        }
        [HttpPost]
        public IActionResult Eliminar(CadeteDTO cadete)
        {
            var accion = repositorioCadete.Eliminar(cadete.Id);
            if (accion)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
    }
}

CadeteriaWeb/CadeteriaWeb/Controllers/ClienteController.cs
using CadeteriaWeb.Models;
using CadeteriaWeb.servicios;
using Microsoft.AspNetCore.Mvc;

namespace CadeteriaWeb.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ILogger<ClienteController> _logger;
        private readonly IRepositorioCliente repositorioCliente;

        public ClienteController(ILogger<ClienteController> logger, IRepositorioCliente repositorioCliente)
        {
            _logger = logger;
            this.repositorioCliente = repositorioCliente;
        }
        public IActionResult Index()
        {
            List<ClienteDTO> clientes = repositorioCliente.listar();
            var modelo = new HomeIndexViewModel()
            {
                ClienteDTOs = clientes
            };
            return View(modelo);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Crear(ClienteDTO clienteDTO)
        {
            repositorioCliente.RegistrarCliente(clienteDTO);
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int idCliente)
        {
            var cliente = repositorioCliente.ObtenerID(idCliente);
            return View(cliente);
        }
        [HttpPost]
        public IActionResult Editar(ClienteDTO cliente)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var accion = repositorioCliente.Editar(cliente);
            if (accion)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Eliminar(int idCliente)
        {
            var cliente = repositorioCliente.ObtenerID(idCliente);
            return View(cliente);
        }
        [HttpPost]
        public IActionResult Eliminar(ClienteDTO cliente)
        {
           
            var accion = repositorioCliente.Eliminar(cliente.Id);
            if (accion)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
    }
}

CadeteriaWeb/CadeteriaWeb/Controllers/HomeController.cs
using CadeteriaWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using CadeteriaWeb.servicios;

namespace CadeteriaWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepositorioCliente repositorioCliente;

        public HomeController(ILogger<HomeController> logger, IRepositorioCliente repositorioCliente)
        {
            _logger = logger;
            this.repositorioCliente = repositorioCliente;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadeteriaWeb/CadeteriaWeb/Views/Cadete/Crear.cshtml
@model CadeteDTO
@{
     ViewData["Title"] = "Crear Cadete";
}
<h1>Registro Cadetes</h1>

<form asp-controller="Cadete" asp-action="Crear" method="post">
     <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input asp-for="nombre" type="text" class="form-control" placeholder="Ej. Clark">
        <span asp-validation-for="nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="apellido" class="form-label">apellido</label>
        <input asp-for="apellido" type="text" class="form-control" placeholder="Ej. Kent">
        <span asp-validation-for="apellido" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="telefono" class="form-label">telefono</label>
        <input asp-for="telefono" type="text" class="form-control" placeholder="381 123 45 67">
        <span asp-validation-for="telefono" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="direccion" class="form-label">Domicilio</label>
        <input asp-for="direccion" type="text" class="form-control" placeholder="Av. Roca 628">
        <span asp-validation-for="direccion" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    <a asp-action="Index" asp-controller="Cadete" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cadete/Editar.cshtml
@model CadeteDTO
@{
    ViewData["title"] = "Editar";
}
<h1>Editar Cadete</h1>

<form asp-controller="Cadete" asp-action="Editar" method="post">
    <input asp-for="Id" type="hidden" class="form-control" >
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input asp-for="nombre" type="text" class="form-control" placeholder="Ej. Clark">
        <span asp-validation-for="nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="apellido" class="form-label">apellido</label>
        <input asp-for="apellido" type="text" class="form-control" placeholder="Ej. Kent">
        <span asp-validation-for="apellido" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="telefono" class="form-label">telefono</label>
        <input asp-for="telefono" type="text" class="form-control" placeholder="381 123 45 67">
        <span asp-validation-for="telefono" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="direccion" class="form-label">Domicilio</label>
        <input asp-for="direccion" type="text" class="form-control" placeholder="Av. Roca 628">
        <span asp-validation-for="direccion" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    <a asp-action="Index" asp-controller="Cadete" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cadete/Eliminar.cshtml
@model CadeteDTO
@{
    ViewData["title"] = "Eliminar";
}
<h1>Eliminar Cadete</h1>

<form asp-controller="Cadete" asp-action="Eliminar" method="post">
    <input asp-for="Id" type="hidden" class="form-control" >
    
    <div class="alert alert-danger" role="alert">
        ¿Desea Borrar el Cadete : @Html.DisplayTextFor(t => t.nombre) ?
    </div>
    
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a asp-action="Index" asp-controller="Cadete" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cadete/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Cadetes";
}

<div class="card">
    <div class="card-header">
        Lista de Cadetes
    </div>
    <div class="card-body">
        <a type="submit" class="btn btn-primary" asp-action="Crear" asp-controller="Cadete" ><i class="bi bi-plus-circle"></i>Crear Cadete</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>apellido</th>
                    <th>nombre</th>
                    <th>direccion</th>
                    <th>telefono</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.CadeteDTOs)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.apellido</td>
                        <td>@item.nombre</td>
                        <td>@item.direccion</td>
                        <td>@item.telefono</td>
                        <td><a asp-action="Editar" asp-controller="Cadete" class="btn btn-primary btn-sm" asp-route-idCliente = "@item.Id">Editar</a></td>
                        <td><a asp-action="Eliminar" asp-controller="Cadete" class="btn btn-primary btn-sm" asp-route-idCliente = "@item.Id">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CadeteriaWeb/CadeteriaWeb/Views/Cliente/Crear.cshtml
@model ClienteDTO
@{
     ViewData["Title"] = "Crear Cliente";
}
<h1>Registro Clientes</h1>

<form asp-controller="Cliente" asp-action="Crear" method="post">
     <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input asp-for="nombre" type="text" class="form-control" placeholder="Ej. Exequiel">
        <span asp-validation-for="nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="apellido" class="form-label">apellido</label>
        <input asp-for="apellido" type="text" class="form-control" placeholder="Ej. Diaz">
        <span asp-validation-for="apellido" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="telefono" class="form-label">telefono</label>
        <input asp-for="telefono" type="text" class="form-control" placeholder="381 123 45 67">
        <span asp-validation-for="telefono" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="direccion" class="form-label">Domicilio</label>
        <input asp-for="direccion" type="text" class="form-control" placeholder="Av. Roca 628">
        <span asp-validation-for="direccion" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    <a asp-action="Index" asp-controller="Cliente" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cliente/Editar.cshtml
@model ClienteDTO
@{
    ViewData["title"] = "Editar";
}
<h1>Editar Cliente</h1>

<form asp-controller="Cliente" asp-action="Editar" method="post">
    <input asp-for="Id" type="hidden" class="form-control" >
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input asp-for="nombre" type="text" class="form-control" placeholder="Ej. Exequiel">
        <span asp-validation-for="nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="apellido" class="form-label">apellido</label>
        <input asp-for="apellido" type="text" class="form-control" placeholder="Ej. Diaz">
        <span asp-validation-for="apellido" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="telefono" class="form-label">telefono</label>
        <input asp-for="telefono" type="text" class="form-control" placeholder="381 123 45 67">
        <span asp-validation-for="telefono" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="direccion" class="form-label">Domicilio</label>
        <input asp-for="direccion" type="text" class="form-control" placeholder="Av. Roca 628">
        <span asp-validation-for="direccion" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    <a asp-action="Index" asp-controller="Cliente" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cliente/Eliminar.cshtml
@model ClienteDTO
@{
    ViewData["title"] = "Eliminar";
}
<h1>Eliminar Cliente</h1>

<form asp-controller="Cliente" asp-action="Eliminar" method="post">
    <input asp-for="Id" type="hidden" class="form-control" >
    
    <div class="alert alert-danger" role="alert">
        ¿Desea Borrar el cliente : @Html.DisplayTextFor(t => t.nombre) ?
    </div>
    
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a asp-action="Index" asp-controller="Cliente" class="btn btn-warning">volver a lista</a>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Cliente/Gracias.cshtml
@{
    ViewData["Title"] = "Gracias";
}

<h1>Gracias por su compra!</h1>
<div><a asp-action="Index" asp-controller="Home">Ir al Home</a></div>

CadeteriaWeb/CadeteriaWeb/Views/Cliente/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Clientes";
}

<div class="card">
    <div class="card-header">
        Lista de Clientes
    </div>
    <div class="card-body">
        <a type="submit" class="btn btn-primary" asp-action="Crear" asp-controller="Cliente" ><i class="bi bi-plus-circle"></i>Crear Cliente</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>apellido</th>
                    <th>nombre</th>
                    <th>direccion</th>
                    <th>telefono</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.ClienteDTOs)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.apellido</td>
                        <td>@item.nombre</td>
                        <td>@item.direccion</td>
                        <td>@item.telefono</td>
                        <td><a asp-action="Editar" asp-controller="Cliente" class="btn btn-primary btn-sm" asp-route-idCliente = "@item.Id">Editar</a></td>
                        <td><a asp-action="Eliminar" asp-controller="Cliente" class="btn btn-primary btn-sm" asp-route-idCliente = "@item.Id">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CadeteriaWeb/CadeteriaWeb/Views/Home/Cliente.cshtml
@{
    ViewData["Title"] = "Clientes";
}

<h1>Registro Clientes</h1>

<form asp-controller="Home" asp-action="Cliente">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ej. Exequiel Diaz">
    </div>
    <div class="mb-3">
        <label for="telefono" class="form-label">telefono</label>
        <input type="text" class="form-control" id="telefono" name="telefono" placeholder="381 123 45 67">
    </div>
    <div class="mb-3">
        <label for="direccion" class="form-label">Domicilio</label>
        <textarea class="form-control" id="direccion" name="direccion" rows="3"></textarea>
    </div>
    <div class="mb-3">
        <label for="detalles" class="form-label">detalles</label>
        <textarea class="form-control" id="detalles" name="detalles" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Registrar</button>
</form>

CadeteriaWeb/CadeteriaWeb/Views/Home/Gracias.cshtml
@{
    ViewData["Title"] = "Gracias";
}

<h1>Gracias por su compra!</h1>

CadeteriaWeb/CadeteriaWeb/Views/Home/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

CadeteriaWeb/CadeteriaWeb/Views/Shared/_Gracias.cshtml
@{
    ViewData["Title"] = "Gracias";
}

<h1>Gracias por su compra!</h1>
<div><a asp-action="Index" asp-controller="Home">Ir al Home</a></div>

CadeteriaWeb/CadeteriaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadeteriaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadeteriaWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadeteriaWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadete" asp-action="Index">Cadetes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CadeteriaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>